//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intento.MT.Plugin.PropertiesForm {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intento.MT.Plugin.PropertiesForm.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your API key and press \&quot;Check\&quot; button..
        /// </summary>
        internal static string ApiKeyNeededErrorMessage {
            get {
                return ResourceManager.GetString("ApiKeyNeededErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key verification in progress .....
        /// </summary>
        internal static string ApiKeyVerificationInProgressMessage {
            get {
                return ResourceManager.GetString("ApiKeyVerificationInProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter credentials.
        /// </summary>
        internal static string AuthWizardFormCaption {
            get {
                return ResourceManager.GetString("AuthWizardFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom credentials (required).
        /// </summary>
        internal static string CustomCredentials {
            get {
                return ResourceManager.GetString("CustomCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a custom model or uncheck \&quot;use your custom model\&quot;.
        /// </summary>
        internal static string CustomModelRequiredMessage {
            get {
                return ResourceManager.GetString("CustomModelRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid API key.
        /// </summary>
        internal static string InvalidApiKeyMessage {
            get {
                return ResourceManager.GetString("InvalidApiKeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKAuthWizardFormLabel {
            get {
                return ResourceManager.GetString("OKAuthWizardFormLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide your own credentials for this provider..
        /// </summary>
        internal static string OwnCredentialsNeededErrorMessage {
            get {
                return ResourceManager.GetString("OwnCredentialsNeededErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hidden text.
        /// </summary>
        internal static string ShowHiddenTextAuthWizardLabel {
            get {
                return ResourceManager.GetString("ShowHiddenTextAuthWizardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to choose a provider.
        /// </summary>
        internal static string YouNeedToChooseAProviderMessage {
            get {
                return ResourceManager.GetString("YouNeedToChooseAProviderMessage", resourceCulture);
            }
        }
    }
}
