//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intento.MT.Plugin.PropertiesForm.WinForms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intento.MT.Plugin.PropertiesForm.WinForms.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmask.
        /// </summary>
        internal static string APIFcheckBoxShowHidden {
            get {
                return ResourceManager.GetString("APIFcheckBoxShowHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intento API Key:.
        /// </summary>
        internal static string APIFlabelAPI {
            get {
                return ResourceManager.GetString("APIFlabelAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your API key and press &quot;Check&quot; button..
        /// </summary>
        internal static string ApiKeyNeededErrorMessage {
            get {
                return ResourceManager.GetString("ApiKeyNeededErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key verification in progress .....
        /// </summary>
        internal static string ApiKeyVerificationInProgressMessage {
            get {
                return ResourceManager.GetString("ApiKeyVerificationInProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to copy error to clipboard.
        /// </summary>
        internal static string APIToolTipMessage {
            get {
                return ResourceManager.GetString("APIToolTipMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter credentials.
        /// </summary>
        internal static string AuthWizardFormCaption {
            get {
                return ResourceManager.GetString("AuthWizardFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Account.
        /// </summary>
        internal static string BillingAccount {
            get {
                return ResourceManager.GetString("BillingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue edit.
        /// </summary>
        internal static string ButtonContinueEdit {
            get {
                return ResourceManager.GetString("ButtonContinueEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore error and save.
        /// </summary>
        internal static string ButtonIgnoreAndSave_Ignore {
            get {
                return ResourceManager.GetString("ButtonIgnoreAndSave_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It’s OK, save settings.
        /// </summary>
        internal static string ButtonIgnoreAndSave_Ok {
            get {
                return ResourceManager.GetString("ButtonIgnoreAndSave_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom credentials (required).
        /// </summary>
        internal static string CustomCredentials {
            get {
                return ResourceManager.GetString("CustomCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a custom model or uncheck &quot;Use your custom model&quot;.
        /// </summary>
        internal static string CustomModelRequiredMessa {
            get {
                return ResourceManager.GetString("CustomModelRequiredMessa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a custom model or uncheck &quot;Use your custom model&quot;.
        /// </summary>
        internal static string CustomModelRequiredMessage {
            get {
                return ResourceManager.GetString("CustomModelRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Intento API key.
        /// </summary>
        internal static string EnterIntentoAPIKey {
            get {
                return ResourceManager.GetString("EnterIntentoAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The answer returned an error.
        /// </summary>
        internal static string ErrorTestTranslation {
            get {
                return ResourceManager.GetString("ErrorTestTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced settings.
        /// </summary>
        internal static string FAcaption {
            get {
                return ResourceManager.GetString("FAcaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization required.
        /// </summary>
        internal static string FAcheckBoxAuth {
            get {
                return ResourceManager.GetString("FAcheckBoxAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable proxy server (Attention! Proxy settings apply to all sets of settings).
        /// </summary>
        internal static string FAcheckBoxProxy {
            get {
                return ResourceManager.GetString("FAcheckBoxProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log translation text for 30 minutes.
        /// </summary>
        internal static string FAcheckBoxTrace {
            get {
                return ResourceManager.GetString("FAcheckBoxTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FAgroupBoxProxySettings {
            get {
                return ResourceManager.GetString("FAgroupBoxProxySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address or host name: http(s)://.
        /// </summary>
        internal static string FAlabelAddress {
            get {
                return ResourceManager.GetString("FAlabelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom name for plugin settings (set blank for default name).
        /// </summary>
        internal static string FAlabelCustomSettingsName {
            get {
                return ResourceManager.GetString("FAlabelCustomSettingsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string FAlabelPassword {
            get {
                return ResourceManager.GetString("FAlabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        internal static string FAlabelPort {
            get {
                return ResourceManager.GetString("FAlabelPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        internal static string FAlabelUserName {
            get {
                return ResourceManager.GetString("FAlabelUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glossary.
        /// </summary>
        internal static string Glossary {
            get {
                return ResourceManager.GetString("Glossary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon intento {
            get {
                object obj = ResourceManager.GetObject("intento", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid API key.
        /// </summary>
        internal static string InvalidApiKeyMessage {
            get {
                return ResourceManager.GetString("InvalidApiKeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string MFbuttonAdvanced {
            get {
                return ResourceManager.GetString("MFbuttonAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string MFbuttonCheck {
            get {
                return ResourceManager.GetString("MFbuttonCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string MFbuttonClose {
            get {
                return ResourceManager.GetString("MFbuttonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change MT Settings.
        /// </summary>
        internal static string MFbuttonMTSetting {
            get {
                return ResourceManager.GetString("MFbuttonMTSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intento plugin settings.
        /// </summary>
        internal static string MFcaption {
            get {
                return ResourceManager.GetString("MFcaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Translation Settings.
        /// </summary>
        internal static string MFgroupBoxMTSettings {
            get {
                return ResourceManager.GetString("MFgroupBoxMTSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You changed ApiKey. We recommend to test MT Settings..
        /// </summary>
        internal static string MFlabelApiKeyIsChanged {
            get {
                return ResourceManager.GetString("MFlabelApiKeyIsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or register at.
        /// </summary>
        internal static string MFlabelRegister1 {
            get {
                return ResourceManager.GetString("MFlabelRegister1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to get one..
        /// </summary>
        internal static string MFlabelRegister2 {
            get {
                return ResourceManager.GetString("MFlabelRegister2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string MFNa {
            get {
                return ResourceManager.GetString("MFNa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Routing (default).
        /// </summary>
        internal static string MFSmartRoutingText {
            get {
                return ResourceManager.GetString("MFSmartRoutingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a model for this provider.
        /// </summary>
        internal static string ModelRequiredMessage {
            get {
                return ResourceManager.GetString("ModelRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Machine Translation.
        /// </summary>
        internal static string MTcaption {
            get {
                return ResourceManager.GetString("MTcaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select MT Provider automatically based on.
        /// </summary>
        internal static string MTcheckBoxSmartRouting {
            get {
                return ResourceManager.GetString("MTcheckBoxSmartRouting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom MT model.
        /// </summary>
        internal static string MTcheckBoxUseCustomModel {
            get {
                return ResourceManager.GetString("MTcheckBoxUseCustomModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom glossary.
        /// </summary>
        internal static string MTcheckBoxUseGlossary {
            get {
                return ResourceManager.GetString("MTcheckBoxUseGlossary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your own MT Provider account.
        /// </summary>
        internal static string MTcheckBoxUseOwnCred {
            get {
                return ResourceManager.GetString("MTcheckBoxUseOwnCred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTIONAL.
        /// </summary>
        internal static string MTgroupBoxOptional {
            get {
                return ResourceManager.GetString("MTgroupBoxOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most of the MT Providers are available via Intento contracts, but you may also use your own account at MT Provider by providing your credentials below..
        /// </summary>
        internal static string MTlabelHelpBillingAccount {
            get {
                return ResourceManager.GetString("MTlabelHelpBillingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of MT Providers enable using your custom terminology or glossary. If you have one, please specify it below..
        /// </summary>
        internal static string MTlabelHelpGlossary {
            get {
                return ResourceManager.GetString("MTlabelHelpGlossary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default, the pre-trained general-purpose MT model is used. If it&apos;s not available or you want to use your custom-trained model, please specify it below..
        /// </summary>
        internal static string MTlabelHelpModel {
            get {
                return ResourceManager.GetString("MTlabelHelpModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will send one-character translation request to test this configuration.
        ///If you have selected custom model or glossary, please adjust the language pair:.
        /// </summary>
        internal static string MTlabelHelpOptional {
            get {
                return ResourceManager.GetString("MTlabelHelpOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Intento Benchmarks..
        /// </summary>
        internal static string MTtextBoxLabelURL {
            get {
                return ResourceManager.GetString("MTtextBoxLabelURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to need a choice....
        /// </summary>
        internal static string NeedAChoise {
            get {
                return ResourceManager.GetString("NeedAChoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKLabel {
            get {
                return ResourceManager.GetString("OKLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide your own credentials for this provider..
        /// </summary>
        internal static string OwnCredentialsNeededErrorMessage {
            get {
                return ResourceManager.GetString("OwnCredentialsNeededErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        internal static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy connection error.
        /// </summary>
        internal static string ProxyConnectionError {
            get {
                return ResourceManager.GetString("ProxyConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hidden text.
        /// </summary>
        internal static string ShowHiddenTextLabel {
            get {
                return ResourceManager.GetString("ShowHiddenTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test and save.
        /// </summary>
        internal static string TestAndSave {
            get {
                return ResourceManager.GetString("TestAndSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We tried to translate &quot;{0}&quot;, but received an unexpected answer &quot;{1}&quot;.
        /// </summary>
        internal static string TestTranslationWarning {
            get {
                return ResourceManager.GetString("TestTranslationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to choose a provider.
        /// </summary>
        internal static string YouNeedToChooseAProviderMessage {
            get {
                return ResourceManager.GetString("YouNeedToChooseAProviderMessage", resourceCulture);
            }
        }
    }
}
