using System;
using System.Collections.Generic;

namespace IntentoMTPlugin
{
    /// <summary>
    /// Helper class to be able to communicate with the web service.
    /// </summary>
    partial class IntentoMTServiceHelper
    {
        List<List<string>> langList = new List<List<string>> {
            new List<String> { "Afrikaans","afr","af","" },
            new List<String> { "Albanian","alb","sq","" },
            new List<String> { "Amrahic","amh","am","Target language only" },
            new List<String> { "Arabic","ara","ar","" },
            new List<String> { "Arabic (Algeria)","ara-DZ","ar-DZ","" },
            new List<String> { "Arabic (Bahrain)","ara-BH","ar-BH","" },
            new List<String> { "Arabic (Egypt)","ara-EG","ar-EG","" },
            new List<String> { "Arabic (Iraq)","ara-IQ","ar-IQ","" },
            new List<String> { "Arabic (Jordan)","ara-JO","ar-JO","" },
            new List<String> { "Arabic (Kuwait)","ara-KW","ar-KW","" },
            new List<String> { "Arabic (Lebanon)","ara-LB","ar-LB","" },
            new List<String> { "Arabic (Libya)","ara-LY","ar-LY","" },
            new List<String> { "Arabic (Morocco)","ara-MA","ar-MA","" },
            new List<String> { "Arabic (Oman)","ara-OM","ar-OM","" },
            new List<String> { "Arabic (Qatar)","ara-QA","ar-QA","" },
            new List<String> { "Arabic (Saudi Arabia)","ara-SA","ar-SA","" },
            new List<String> { "Arabic (Syria)","ara-SY","ar-SY","" },
            new List<String> { "Arabic (Tunisia)","ara-TN","ar-TN","" },
            new List<String> { "Arabic (U.A.E.)","ara-AE","ar-AE","" },
            new List<String> { "Arabic (Yemen)","ara-YE","ar-YE","" },
            new List<String> { "Armenian","hye","hy","" },
            new List<String> { "Assamese","asm","as","" },
            // new List<String> { "Assamese","ibo","ig","" },
            new List<String> { "Azeri (Cyrillic)","azf","az-Cyrl","" },
            new List<String> { "Azeri (Latin)","aze","az","" },
            new List<String> { "Basque","baq","eu","" },
            new List<String> { "Belarussian","bel","be","" },
            new List<String> { "Bengali","ben","bn","" },
            new List<String> { "Bengali (Bangladesh)","ben-BD","bn-BD","" },
            new List<String> { "Bengali (India)","ben-IN","bn-IN","" },
            new List<String> { "Bislama","bis","bi","" },
            new List<String> { "Bosnian (Cyrillic)","boc","bs-Cyrl","" },
            new List<String> { "Bosnian (Latin)","bos","bs-Latn","" },
            new List<String> { "Bulgarian","bul","bg","" },
            new List<String> { "Burmese","mya","my","Target language only" },
            new List<String> { "Catalan","cat","ca","" },
            new List<String> { "Chin","ctd","ctd","" },
            new List<String> { "Chinese (Hong Kong S.A.R.)","zho-HK", "zh-hant", "" },
            new List<String> { "Chinese (Macao S.A.R.)","zho-MO", "zh-hant", "" },
            new List<String> { "Chinese (PRC)","zho-CN","zh","" },
            new List<String> { "Chinese (Singapore)","zho-SG", "zh", "" },
            new List<String> { "Chinese (Taiwan)","zho-TW", "zh-hant", "" },
            new List<String> { "Croatian","hrv","hr","" },
            new List<String> { "Czech","cze","cs","" },
            new List<String> { "Danish","dan","da","" },
            new List<String> { "Dari","prs","prs-AF","" },
            new List<String> { "Dinka","din","din","" },
            new List<String> { "Dutch","dut","nl","" },
            new List<String> { "Dutch (Belgium)","dut-BE","nl-be","" },
            new List<String> { "Dutch (Netherlands)","dut-NL","nl-nl","" },
            new List<String> { "English","eng","en","" },
            new List<String> { "English (Australia)","eng-AU","en-au","" },
            new List<String> { "English (Belize)","eng-BZ","en-bz","" },
            new List<String> { "English (Canada)","eng-CA","en-ca","" },
            new List<String> { "English (Caribbean)","eng-CB","en-029","" },
            new List<String> { "English (Ireland)","eng-IE","en-ie","" },
            new List<String> { "English (Jamaica)","eng-JM","en-jm","" },
            new List<String> { "English (New Zealand)","eng-NZ","en-nz","" },
            new List<String> { "English (Republic of the Philippines)","eng-PH","en-ph","" },
            new List<String> { "English (South Africa)","eng-ZA","en-za","" },
            new List<String> { "English (Trinidad and Tobago)","eng-TT","en-tt","" },
            new List<String> { "English (United Kingdom)","eng-GB","en-gb","" },
            new List<String> { "English (United States)","eng-US","en-us","" },
            new List<String> { "English (Zimbabwe)","eng-ZW","en-zw","" },
            new List<String> { "Esperanto","epo","eo","" },
            new List<String> { "Estonian","est","et","" },
            new List<String> { "Farsi","fas","fa","" },
            new List<String> { "Fijian","fij","fj","" },
            new List<String> { "Filipino","fil","fil","" },
            new List<String> { "Finnish","fin","fi","" },
            new List<String> { "Flemish","vls","vls","" },
            new List<String> { "French","fre","fr","" },
            new List<String> { "French (Belgium)","fre-BE","fr-be","" },
            new List<String> { "French (Canada)","fre-CA","fr-ca","" },
            new List<String> { "French (France)","fre-FR","fr-fr","" },
            new List<String> { "French (Luxembourg)","fre-LU","fr-lu","" },
            new List<String> { "French (Monaco)","fre-MC","fr-mc","" },
            new List<String> { "French (Switzerland)","fre-CH","fr-ch","" },
            new List<String> { "Frisian","Western","fry","fy","" },
            new List<String> { "Gaelic (Scotland)","gla","gd","" },
            new List<String> { "Galician","glg","gl","" },
            new List<String> { "Georgian","kat","ka","" },
            new List<String> { "German","ger","de","" },
            new List<String> { "German (Austria)","ger-AT","de-at","" },
            new List<String> { "German (Germany)","ger-DE","de-de","" },
            new List<String> { "German (Liechtenstein)","ger-LI","de-li","" },
            new List<String> { "German (Luxembourg)","ger-LU","de-lu","" },
            new List<String> { "German (Switzerland)","ger-CH","de-ch","" },
            new List<String> { "Greek","gre","el","" },
            new List<String> { "Gujarati","guj","gu","" },
            new List<String> { "Haitian Creole","hat","ht","" },
            new List<String> { "Hausa","hau","ha-Latn","" },
            new List<String> { "Hazaragi","haz","haz","" },
            new List<String> { "Hebrew","heb","he","" },
            new List<String> { "Hindi","hin","hi","" },
            new List<String> { "Hmong","hmn","hmn","" },
            new List<String> { "Hungarian","hun","hu","" },
            new List<String> { "Icelandic","ice","is","" },
            new List<String> { "Igbo","ibo","ig","" },
            new List<String> { "Indonesian","ind","id","" },
            new List<String> { "Irish","gle","ga","" },
            new List<String> { "Italian","ita","it","" },
            new List<String> { "Italian (Italy)","ita-IT","it-it","" },
            new List<String> { "Italian (Switzerland)","ita-CH","it-ch","" },
            new List<String> { "Japanese","kan","kn","" },
            new List<String> { "Javanese","jpn","ja","" },
            // new List<String> { "Kannada","kan","kn","" },
            new List<String> { "Karen","ksw","ksw","Target language only" },
            new List<String> { "Kashmiri","kas","ks","" },
            new List<String> { "Kayah (Latin)","kyu","kyu-Latn","" },
            new List<String> { "Kayah (Myanmar)","eky","eky-Mymr","Target language only" },
            new List<String> { "Kazakh","kaz","kk","" },
            new List<String> { "Khmer","khm","km","Target language only" },
            new List<String> { "Kiribati","gil","gil","" },
            new List<String> { "Klingon","qqq","qqq","" },
            new List<String> { "Korean","kor","ko","" },
            new List<String> { "Kurdish (Arabic)","ckb","ku-Arab","" },
            new List<String> { "Kurdish (Cyrillic)","kmr","ku-Cyrl","" },
            new List<String> { "Kurdish (Latin)","kur","ku-Latn","" },
            new List<String> { "Kyrgyz (Cyrillic)","kir","ky","" },
            new List<String> { "Lao","lao","lo","Target language only" },
            new List<String> { "Latin","lat","la","" },
            new List<String> { "Latvian","lav","lv","" },
            new List<String> { "Lingala","lin","ln","" },
            new List<String> { "Lithuanian","lit","lt","" },
            new List<String> { "Luxembourgish","ltz","lb","" },
            new List<String> { "Macedonian","mac","mk","" },
            new List<String> { "Malagasy","mlg","mg","" },
            new List<String> { "Malay","msa","ms","" },
            new List<String> { "Malayalam","mal","ml","" },
            new List<String> { "Maltese","mlt","mt","" },
            new List<String> { "Mandinka (Arabic)","mno","mnk-Arab","" },
            new List<String> { "Mandinka (Latin)","mnk","mnk-Latn","" },
            new List<String> { "Maori","mri","mi","" },
            new List<String> { "Marathi","mar","mr","" },
            new List<String> { "Marshallese","mah","mh","" },
            new List<String> { "Moldavian","mol","mo","" },
            new List<String> { "Mon","mnw","mnw","Target language only" },
            new List<String> { "Mongolian (Cyrillic)","khk","mn","" },
            new List<String> { "Montenegrin (Cyrillic)","cgy", "cnr-cyrl", "" },
            new List<String> { "Montenegrin (Latin)","cgl", "cnr-latn", "" },
            new List<String> { "Nauruan","nau","na","" },
            new List<String> { "Nepali","nep","ne","" },
            new List<String> { "Norwegian","nor","no","" },
            new List<String> { "Norwegian (Bokmål)", "nnb","nb","" },
            new List<String> { "Norwegian (Nynorsk)","nno","nn","" },
            new List<String> { "Oriya","ori","or","" },
            new List<String> { "Pashto","pbu","ps","" },
            new List<String> { "Pijin","pis","pis","" },
            new List<String> { "Polish","pol","pl","" },
            new List<String> { "Portuguese","por","pt","" },
            new List<String> { "Portuguese (Brazil)","por-BR","pt-br","" },
            new List<String> { "Portuguese (Portugal)","por-PT","pt-pt","" },
            new List<String> { "Punjabi (Gurmukhi)","pan","pa","" },
            new List<String> { "Punjabi (Shahmuki)","pnb","pa-Arab","" },
            new List<String> { "Rohingya","rhg","rhg","" },
            new List<String> { "Romanian","rum","ro","" },
            new List<String> { "Rundi","run","rn","" },
            new List<String> { "Russian","rus","ru","" },
            new List<String> { "Rwanda","kin","rw-RW","" },
            new List<String> { "Samoan","smo","sm","" },
            new List<String> { "Sanskrit","san","sa","" },
            new List<String> { "Serbian (Cyrillic)","scc","sr-cyrl","" },
            new List<String> { "Serbian (Latin)","scr","sr-latn","" },
            new List<String> { "Sesotho","sot","st","" },
            new List<String> { "Shan","shn","shn","Target language only" },
            new List<String> { "Sinhala","sin","si","" },
            new List<String> { "Slovak","slo","sk","" },
            new List<String> { "Slovenian","slv","sl","" },
            new List<String> { "Somali","som","so","" },
            new List<String> { "Somali (Djibouti)","som-DJ","so-dj","" },
            new List<String> { "Somali (Ethiopia)","som-ET","so-et","" },
            new List<String> { "Somali (Kenya)","som-KE","so-ke","" },
            new List<String> { "Somali (Somalia)","som-SO","so-so","" },
            new List<String> { "Spanish","spa","es","" },
            new List<String> { "Spanish (Argentina)","spa-AR","es-ar","" },
            new List<String> { "Spanish (Bolivia)","spa-BO","es-bo","" },
            new List<String> { "Spanish (Chile)","spa-CL","es-cl","" },
            new List<String> { "Spanish (Colombia)","spa-CO","es-co","" },
            new List<String> { "Spanish (Costa Rica)","spa-CR","es-cr","" },
            new List<String> { "Spanish (Dominican Republic)","spa-DO","es-do","" },
            new List<String> { "Spanish (Ecuador)","spa-EC","es-ec","" },
            new List<String> { "Spanish (El Salvador)","spa-SV","es-sv","" },
            new List<String> { "Spanish (Guatemala)","spa-GT","es-gt","" },
            new List<String> { "Spanish (Honduras)","spa-HN","es-hn","" },
            new List<String> { "Spanish (Latin America)","spa-M9","es-la","" },
            new List<String> { "Spanish (Mexico)","spa-MX","es-mx","" },
            new List<String> { "Spanish (Nicaragua)","spa-NI","es-ni","" },
            new List<String> { "Spanish (Panama)","spa-PA","es-pa","" },
            new List<String> { "Spanish (Paraguay)","spa-PY","es-py","" },
            new List<String> { "Spanish (Peru)","spa-PE","es-pe","" },
            new List<String> { "Spanish (Puerto Rico)","spa-PR","es-pr","" },
            new List<String> { "Spanish (Spain)","spa-ES","es-es","" },
            new List<String> { "Spanish (United States)","spa-US","es-us","" },
            new List<String> { "Spanish (Uruguay)","spa-UY","es-uy","" },
            new List<String> { "Spanish (Venezuela)","spa-VE","es-ve","" },
            new List<String> { "Sudanese Creole Arabic","pga","pga","" },
            new List<String> { "Sundanese","sun","su","" },
            new List<String> { "Swahili","swa","sw","" },
            new List<String> { "Swedish","swe","sv","" },
            new List<String> { "Swedish (Finland)","swe-FI","sv-fi","" },
            new List<String> { "Swedish (Sweden)","swe-SE","sv-se","" },
            new List<String> { "Tagalog","tgl","tl","" },
            new List<String> { "Tajiki (Cyrillic)","tgk","tg-Cyrl","" },
            new List<String> { "Tamazight","tzm","tzm-Latn","" },
            new List<String> { "Tamil","tam","ta","" },
            new List<String> { "Telugu","tel","te","" },
            new List<String> { "Tetun Dili","tdt","tdt","" },
            new List<String> { "Thai","tha","th","Target language only" },
            new List<String> { "Tigrigna","tir","ti-ET","Target language only" },
            new List<String> { "Tok Pisin","tpi","tpi","" },
            new List<String> { "Tongan","ton","to","" },
            new List<String> { "Torres Strait Creole","tcs","tcs","" },
            new List<String> { "Tswana","tsn","tn-BW","" },
            new List<String> { "Turkish","tur","tr","" },
            new List<String> { "Turkmen (Latin)","tuk","tk","" },
            new List<String> { "Tuvaluan","tvl","tvl","" },
            new List<String> { "Ukrainian","ukr","uk","" },
            new List<String> { "Urdu","urd","ur","" },
            new List<String> { "Uzbek (Cyrillic)","uzn","uz","" },
            new List<String> { "Uzbek (Latin)","uzb","uz-Latn-UZ","" },
            new List<String> { "Vietnamese","vie","vi","" },
            new List<String> { "Welsh","wel","cy","" },
            new List<String> { "Xhosa","xho","xh","" },
            new List<String> { "Yiddish","yid","yi","" },
            new List<String> { "Yoruba","yor","yo","" },
            new List<String> { "Zulu","zul","zu","" }
            };
    }
}